### ISSUE TITLE
example.cpp does not work

### ISSUE THREAD

**Issue by xyang619** [mandreyel/mio#12]
I have tried the example.cpp and it compiled successfully. However when I try to run it, it does not work.
```
$ g++ example.cpp -Wall -std=c++11 -I ../include -o example
$ ./example
```
The error message is:

> error mapping file: No such file or directory, exiting...

then I tried to touch a file named file.txt，another error occured.
```
$ touch file.txt
$ ./example
```
> error mapping file: Invalid argument, exiting...

Platform Linux Debian 9 .5
gcc version 6.3.0 20170516 (Debian 6.3.0-18+deb9u1)

Thanks

**Comment by mandreyel** [comment]
@xyang619 Thanks for using mio and reporting this. I compiled it with the same compilation commands and on my platform (Arch with most recent updates installed) the example as well as the tests run as expected, no errors. I'm not sure what caused the issue for you. Perhaps something with permissions?

**Comment by xyang619** [comment]
@mandreyel Thanks for your quick response. I checked the permission and I do have read and write permission.  I will check it further.

**Comment by mandreyel** [comment]
@xyang619 I just had the chance to run it on a similar Debian platform and it indeed does not run as expected. I'm looking into it now!

**Comment by mandreyel** [comment]
@xyang619 Having thought some more about it, I have come to find the idea of silently allocating the file a bad idea. Memory mapping, to my understanding, is about creating a memory *view* into a file, and to view something, that something must already exist. At least I find this more intuitive and less surprising than silent allocations.
So I'm going to close this for now, but if more people wish to change this behavior, I'll reconsider my decision.
Thanks for your input, it helped me to clarify the example and the docs!
