### ISSUE TITLE
Consider making mio single-header

### ISSUE THREAD

**Issue by mandreyel** [mandreyel/mio#23]
As suggested by https://news.ycombinator.com/item?id=18264141, it seems like it would be nice to make mio, or at least provide the option, to make mio a single-header library. I'd like to avoid changing the actual project structure (that is, I want to keep the current files separate), so this could be done in the build phase.

**Comment by myd7349** [comment]
May be [Amalgamate](https://github.com/vinniefalco/Amalgamate) will be helpful.

**Comment by mandreyel** [comment]
@myd7349 Oh, nice! I wasn't aware of this, this would indeed be helpful. Thanks a lot for bringing it to my attention!

**Comment by myd7349** [comment]
@mandreyel You may also take a glance at [amalgamate.py](https://github.com/edlund/amalgamate).

[nlohmann/json](https://github.com/nlohmann/json/tree/develop/third_party/amalgamate) uses this tool to create a single header only library.

**Comment by mandreyel** [comment]
@myd7349 Thanks again! :) I'm sorry for not acting on the original suggestion, I have had zero time/energy lately to do OSS stuff after work, but I haven't forgotten this. Although if you want to and have time, I'd be glad for a PR!

**Comment by myd7349** [comment]
[Clara](https://github.com/catchorg/Clara) uses a Python script to generate a single header library: [stitch.py](https://github.com/catchorg/Clara/blob/master/scripts/stitch.py).

Hoo! We have so many choices.
