### ISSUE TITLE
Add madvise support

### ISSUE THREAD

**Issue by mandreyel** [mandreyel/mio#3]

**Comment by mandreyel** [comment]
I added a [branch](https://github.com/mandreyel/mio/tree/cache-hint) that implements this but I'm not sure about the API yet. If anyone is checking this out, I'd really appreciate some feedback.

**Comment by amallia** [comment]
Madvise can actually be called anyway be the programmer after invoking you library. So not sure if it is a priority, is it?

Anyway, I think either a template tag or a parameter passed to the map function is fine.

**Comment by mandreyel** [comment]
@amallia Thank you for chiming in!
Yes, that is true for POSIX, but as far as I know, Windows has unfortunately no such equivalent--you have to provide the file cache hint when opening a file handle, i.e. when calling [`CreateFileA`](https://docs.microsoft.com/en-us/windows/desktop/api/fileapi/nf-fileapi-createfilea).

But since then I've realized that this would break the symmetry of the API, in that one wouldn't be able to specify the cache hint on Windows when opening a mapping with an existing file handle.

So you're probably right in that if a user wanted this feature, it's trivial to just call: `madvise(mmap.data() - mmap.offset(),  mmap.mapped_length(), MADV_RANDOM)`, and on Windows they'd need to open the file handle themselves with the desired flags. Not the best, considering my goal was abstracting away the need to differentiate between operating systems, but it will have to do.
