### ISSUE TITLE
libzippp::ZipArchive seems to be just support utf8 ....

### ISSUE THREAD

**Issue by aijyo** [mandreyel/mio#33]
Just as the title, when use libzippp to commpress some file with  Chinese in path(not just ANSI) failed,  through the source code i find it seems to be just support utf8....
So,  I think it can wrap a transcode to support  tstring... not utf8
![image](https://user-images.githubusercontent.com/7956449/48322600-5c549d00-e663-11e8-9c6e-3a83657f3230.png)

**Comment by mandreyel** [comment]
@aijyo Thanks for filing the issue. I'm not sure I fully understand what's happening here, but it seems like you're trying to use `wchar_t*` as the path type, which is an outstanding issue (#19). Correct me if I'm wrong.

**Comment by aijyo** [comment]
> @aijyo Thanks for filing the issue. I'm not sure I fully understand what's happening here, but it seems like you're trying to use `wchar_t*` as the path type, which is an outstanding issue (#19). Correct me if I'm wrong.

Yes, I am using wchar_t* and not UTF8 encoding...

**Comment by mandreyel** [comment]
@aijyo I was meaning to fix it but I hit a wall with the template meta programming that's required to make this work. If you're good at that, I'd be grateful for a PR, otherwise I'll try to conjure up something this week.

**Comment by aijyo** [comment]
I will consider how to solve this problem. If there is a suitable answer, I will tell you.

**Comment by mandreyel** [comment]
@aijyo Alright. I'll also look into this later today.

**Comment by mandreyel** [comment]
@aijyo Alright. I'll also look into this later today.

**Comment by mandreyel** [comment]
@aijyo I'm sorry if I misunderstood something, but I don't see where mio comes into play in the above code. Could you please provide more info?

**Comment by aijyo** [comment]
> @aijyo I'm sorry if I misunderstood something, but I don't see where mio comes into play in the above code. Could you please provide more info?

I'll sorry ...now I'm wondering why I'm discussing libzipp issue under  mio project(sick, dizzy..) , It's time to close it

**Comment by aijyo** [comment]
Wrong question submission

**Comment by mandreyel** [comment]
@aijyo Haha, no worries! It sounded like a valid question because mio does not support `wchar_t*` paths either. Get well soon!

**Comment by aijyo** [comment]
Thanks~ I'm now use libzippp compress file, and then use mio to read big file chunk to sync file between client & server...  So  something goes wrong

**Comment by mandreyel** [comment]
@aijyo As in, there is something wrong with mio after all?

**Comment by aijyo** [comment]
> @aijyo As in, there is something wrong with mio after all?
(I'm meaning submission wrong)
but as you mentioned,  It's not so easy to use the mio with tstring(when unicode , wchar_t* ),I must transcode the tstring to ansi(just like the follow img)... because open_file using createfileA open the dest file,  why not using template specialization to deal with std::wstring...


![image](https://user-images.githubusercontent.com/7956449/48400723-1d594100-e762-11e8-82e7-ed311efcf4e5.png)

**Comment by mandreyel** [comment]
@aijyo Yeah, this is what I meant by `wchar_t` based strings being an outstanding issue. I tried to solve this with template metaprogramming shenanigans but hit a wall. The problem is that I use templates to accept both C style strings and C++ container based strings, and I'm using [this](https://github.com/mandreyel/mio/blob/master/include/mio/detail/string_util.hpp#L30) template struct for SFINAE. There would need to be an overload that compares against the various char types. Let me try a brute force solution.

**Comment by aijyo** [comment]
> @aijyo Yeah, this is what I meant by `wchar_t` based strings being an outstanding issue. I tried to solve this with template metaprogramming shenanigans but hit a wall. The problem is that I use templates to accept both C style strings and C++ container based strings, and I'm using [this](https://github.com/mandreyel/mio/blob/master/include/mio/detail/string_util.hpp#L30) template struct for SFINAE. There would need to be an overload that compares against the various char types. Let me try a brute force solution.

Looking forward to your implemention.

**Comment by mandreyel** [comment]
@aijyo Created a PR for this (#34). Could you please check it out?

**Comment by linliangpei** [comment]
mio无法映射中文路径文件，请问解决这个问题了吗？
