### ISSUE TITLE
Advise: When map_entir_file, the len of file to map including the offset may  be more appropriate

### ISSUE THREAD

**Issue by aijyo** [mandreyel/mio#35]
Just as the title:  
in some condition, we need map entire file from the offset. 

In addition, if offset>0, map the entire file length is not appropriate。

I modified the corresponding file locally：
![image](https://user-images.githubusercontent.com/7956449/48926880-9a2bae00-ef0c-11e8-82a9-e85250942a3c.png)

**Comment by mandreyel** [comment]
@aijyo Oops, that's a bug indeed. Thanks a lot for filing this!
