### ISSUE TITLE
Add support to handle any type of objects .

### ISSUE THREAD

**Issue by Saira-Mughal** [mandreyel/mio#36]
@mandreyel  ..Currently i can access only char (or any type of same width of char) by index but there should be option to specify any data type including user defined Classes to access via index from mapped file.

**Comment by Wunkolo** [comment]
In a pointer-wrapper utility class I implemented a while ago for a project I had added a templated "data()" method that allows you to pass the type of the pointer you want it to cast into:
```
data<MyStruct>()[5] = MyStruct( 0xbeef, true, "blah" );
```
Maybe something like this can be added to the already-existing method?
```cpp
    // Untested code, just to illustrate
    template<
        typename cast_type = value_type,
        access_mode A = AccessMode,
        typename = typename std::enable_if<A == access_mode::write>::type
    > cast_type* data() noexcept { return reinterpret_cast<cast_type*>(data_); }
```
