### ISSUE TITLE
memory leak 

### ISSUE THREAD

**Issue by shivendra14** [mandreyel/mio#55]
seems the file is not unmaped and closed in the function.
please do the cleanup.

![image](https://user-images.githubusercontent.com/3680192/66219268-7ae2dd00-e6e8-11e9-9acd-288c5133a43f.png)

**Comment by VioletGiraffe** [comment]
May I ask which tool you've used to perform this analysis?

**Comment by shivendra14** [comment]
@VioletGiraffe : I used coverity

**Comment by mandreyel** [comment]
Good catch, thanks! Fixed in latest commit. Sorry about the delay, was massively overwhelmed with everything.
