### ISSUE TITLE
build failure: add_executable cannot create target "mio.fullwinapi.test"

### ISSUE THREAD

**Issue by slaweks17** [mandreyel/mio#58]
Hi,
I followed the instructions, but failed:

cmake -G "Visual Studio 16 2019" ..
-- The C compiler identification is MSVC 19.24.28314.0
-- The CXX compiler identification is MSVC 19.24.28314.0
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.24.28314/bin/Hostx64/x64/cl.exe
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.24.28314/bin/Hostx64/x64/cl.exe -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.24.28314/bin/Hostx64/x64/cl.exe
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.24.28314/bin/Hostx64/x64/cl.exe -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Error at test/CMakeLists.txt:21 (add_executable):
  add_executable cannot create target "mio.fullwinapi.test" because another
  target with the same name already exists.  The existing target is an
  executable created in source directory "D:/progs/c++/mio/test".  See
  documentation for policy CMP0002 for more details.

**Comment by mandreyel** [comment]
Thanks for reporting, and sorry for the delay.

This seems to have been fixed by #63. Let me know if it still doesn't work.
