### ISSUE TITLE
Is it threadsafe?

### ISSUE THREAD

**Issue by pps83** [mandreyel/mio#59]
I assume it is, but without knowing impl details I cannot be sure about it.
If I create mapping:
`mio::mmap_source mmap = mio::make_mmap_source(filePath, error);`
can I then access `mmap` from multiple threads to read the file without synchronizing access to it?

**Comment by mandreyel** [comment]
Yes, I think this should be the case for read-only mappings, since all threads should be referring to a single memory area in the kernel page cache.

**Comment by pps83** [comment]
> Yes, I think this should be the case for read-only mappings, since all threads should be referring to a single memory area in the kernel page cache.

Yes, all the threads will use the same memory area assuming that all of it gets mapped when constructing `mmap` object. But will it it be threadsafe to access the `mmap` object if the pages are loaded on demand? In that case, multiple threads will trigger page loads simultaneously for different regions. That was the point of the question.

**Comment by Wunkolo** [comment]
> But will it it be threadsafe to access the `mmap` object if the pages are loaded **on demand**? In that case, **multiple threads will trigger page loads simultaneously for different regions**. That was the point of the question.

This is fine. It's is an implementation detail of how the operating system handle in-flight page-faults. If multiple threads asynchronously trigger a page-fault for parts of the same file, the kernel will only load in the union of all the exclusive pages that need to be streamed in. Loading in these page-faults involves a full context-switch-out->stream->context-switch-in. Which is inherently thread safe. I currently use this pattern to unpack a large game archive file across multiple threads.
Multiple threads creating page-faults will just cause the kernel to stream in the data and update the process's virtual memory map and the target page will then become fully resident and the threads wouldn't be any wiser to what just happened(it will appear as if it was always there the whole time, as far as the process is concerned).

So yes, reading a memory-mapped file across multiple threads will work just fine. Can't say much about the performance though as that will depend on the underlying device and how the kernel handles it.
