### ISSUE TITLE
Does this work with threads?

### ISSUE THREAD

**Issue by ruler501** [mandreyel/mio#79]
I have a large file which is a binary array of structs that I want to process in parallel would this work with multiple threads reading from the memmapped file?

**Comment by Wunkolo** [comment]
Yes. I personally do this with [Maple2Tools](https://github.com/Wunkolo/Maple2Tools).
Once you map the memory. It's just like any other page of memory and you can have multiple threads reading from it in parallel with no need for synchronization.

**Comment by ruler501** [comment]
Great thank you.
