### ISSUE TITLE
Search through mapped file line by line

### ISSUE THREAD

**Issue by JAWilliams123** [mandreyel/mio#92]
Hello,

Many thanks for sharing the mapping header. Is there a way to loop through the mapped text file line by line of the text? I have a huge data file mapped but would like to search through the various lines of text. It was simple to search using getline and a std::vector to store each line but building the vector is initially very slow.  

Many thanks,
JW

**Comment by spudwa** [comment]
getline(...) just searches through the file for newline characters '\n' which delimits the line of text. You just have to do the same using something like strtok().

**Comment by JAWilliams123** [comment]
Many thanks @spudwa.
I have created a read-only map with the following code:

`mio::mmap_source ro_mmap;`
`ro_mmap.map(FileName, error);`
 
But I am not certain how to access the mapped contents using strtok(). I can establish the string and get the first token using: `char *token = strtok(ro_mmap, " \n");`. Any suggestions on how `ro_mmap` can be accessed using strtok?

Many thanks,
JW

**Comment by spudwa** [comment]
I use this code in my program to map a file of structs. This converts the blob of data in the mmap into something I can use
GENOME_MODEL_10 *pGM10 = reinterpret_cast<GENOME_MODEL_10*>(map_gm10.data());

so I assume you could use

char *line = reinterpret_cast<char*>(ro_mmap.data());
char *token = strtok(line, "\n");

**Comment by JAWilliams123** [comment]
Many thanks again!

I will have a go later today and let you know how I get on.

Best wishes,
JW

**Comment by spudwa** [comment]
forgot '*'
char *line = reinterpret_cast<char *>(ro_mmap.data());
char *token = strtok(line, "\n");

**Comment by JAWilliams123** [comment]
Ok, ro_mmap.data() points me to the first bit of text but I am not able to progress through the rest of the data with a while loop and strtok. Should I perhaps be using reinterpret_cast while iterating through ro_mmap?

Many thank,
JW

**Comment by spudwa** [comment]
as I said the mmap is just a blob of data. Your need the reinterpret_cast to tell the compiler that you 'know' the data is char data and then the pointer to mmap becomes a pointer to char which is what you need for strtok

**Comment by JAWilliams123** [comment]
Hello @spudwa,

My issue was being caused by strtok_s editing my file by adding NULL. I have done a work around by copying the reinterpret_cast line variable and them operating on it. 
Many thanks again for your help on this one.

Best wishes,
JW
